apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
  namespace: NAMESPACE
  labels:
    app: guestbook-ui
spec:
  type: ClusterIP
  selector:
    app: guestbook-ui
  ports:
  - name: http
    port: 9898
    protocol: TCP
    targetPort: http