apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
  config.json: |-
    {
      "idp_name": "http://simple-oidc-provider.tpw:9000",
      "port": 9000,
      "client_config": [ {{- range $index, $client := .Values.clients }}
        {{- if $index }},{{- end}}
        {
            "client_id": "{{ $client.client_id }}",
            "client_secret": "{{ $client.client_secret }}",
            "redirect_uris": [
                "{{ $client.redirect_url }}"
            ]
        }{{- end }}
      ],
      "claim_mapping": {
        "openid": [ "sub" ],
        "email": [ "email", "email_verified" ],
        "profile": [ "name", "nickname" ]
      }
    }