apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-oidc
  template:
    metadata:
      labels:
        app: simple-oidc
    spec:
      containers:
      - image: qlik/simple-oidc-provider:latest
        name: simple-oidc
        ports:
        - containerPort: 9000
