apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-oidc
  template:
    metadata:
      labels:
        app: simple-oidc
    spec:
      containers:
      - image: qlik/simple-oidc-provider:latest
        name: simple-oidc
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: config-file
          mountPath: /etc/config
        env:
        - name: CONFIG_FILE
          value: /etc/config/config.json
      volumes:
      - name: config-file
        configMap:
          name: {{ .Release.Name }}
          
